db:
  driver: "mysql"
  host: ""
  username: ""
  password: ""
  database: ""
ldap:
  host: "pm-ns.mozilla.org"
  port: 389
  bind_dn: ""
  bind_password: ""
ssl:
  enforced: true
mail:
  enabled: true
  from: "sheriffbot@mozilla.com"
ical:
  enabled: true

